version: 2.1
jobs:
  build:
    docker:
      image: circleci/node:12.14.0
    steps:
      - checkout
      - run: "npm install"
      - run:
          name: "Running tests"
          command: "npm test"
