version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
jobs:
  build:
      docker:
        - image: circleci/node:12.14.0
      steps:
        - checkout
        - run: npm install
        - run: npm test
